name: bpjs_barcodescanner
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  firebase_database: ^10.4.5
  shared_preferences: ^2.0.11
  barcode_scan2: ^4.1.1
  mobile_scanner: ^3.5.1 
  image_picker: ^1.0.4
  firebase_storage: ^11.5.3
  http: ^0.13.5
  path_provider: ^2.1.1
  flutter_dotenv: ^5.0.2
  msal_flutter: ^3.0.0 # Gunakan versi terbaru yang tersedia
  flutter_secure_storage: ^9.0.0 # Gunakan versi terbaru yang tersedia

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1 

flutter:
  uses-material-design: true
  assets:
    - lib/img/bpjs.png
    - lib/img/bpjs2.png 

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "lib/img/bpjs2.png"
